# Generated by Django 6.0.2 on 2026-03-05 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_membership_status_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPaySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('autopay_status', models.CharField(choices=[('ENABLED', 'Enabled'), ('CANCELLED', 'Cancelled')], default='ENABLED', max_length=15)),
                ('current_cycle_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=15)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autopay_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
