# Generated by Django 6.0.2 on 2026-03-08 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_autopaysubscription_next_billing_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersession',
            name='core_userse_session_5d2ebc_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='core_userse_user_id_11c81c_idx',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='refresh_token_hash',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_agent',
        ),
    ]
