# Generated by Django 6.0.2 on 2026-03-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_branch_venture_redemption_branch_venture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVoucher',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
