# Generated by Django 6.0.2 on 2026-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_uservoucher_delete_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='icon',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='ventures/icons/'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='poster',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='ventures/posters/'),
        ),
    ]
