# Generated by Django 6.0.2 on 2026-03-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_profile_pic_alter_venture_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='poster_public_id',
        ),
    ]
